Drop nox in favor of vanilla scripts (#19)
* Drop nox in favor of vanilla scripts

* Update Python versions on CI

* Fix dependency resolution

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -13,9 +13,15 @@ if ! command -v "${PREFIX}twine" &>/dev/null ; then
     exit 1
 fi
 
+if ! ${PREFIX}pip show wheel &>/dev/null ; then
+    echo "Unable to find the 'wheel' command."
+    echo "Install from PyPI, using '${PREFIX}pip install wheel'."
+    exit 1
+fi
+
 scripts/clean
 
-${PREFIX}python setup.py sdist
+${PREFIX}python setup.py sdist bdist_wheel
 ${PREFIX}twine upload dist/*
 
 echo "You probably want to also tag the version now:"
